import type { Metadata } from "next";
import { Fredoka, Poppins } from "next/font/google";
import "./globals.css";
import MainProviders from "@/Providers/MainProviders";
import Provider from "@/Providers/Provider";
import { Toaster } from "sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Book genarator",
  description: "Generated by create sahara",
=======
  title: "Build Story Time",
  description: "Build your story with ai, create your own book by using your custom voice and reference image.",
>>>>>>> f276b233df551b217c1b3997a8efd66b9587ebe5
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${poppins.variable} ${fredoka.variable} antialiased`}
      >
         
=======
      <body className={`${poppins.variable} ${fredoka.variable} antialiased`}>
>>>>>>> f276b233df551b217c1b3997a8efd66b9587ebe5
        <MainProviders>
          <Provider> {children} </Provider>
        </MainProviders>
        <Toaster position="top-right" closeButton />
      </body>
    </html>
  );
}
